import type { Vec3, Int3 } from "../math/vec";
import type { AtomSite, Lattice } from "./types";
import { fracToCart, intToCart } from "../math/vec";
import { displayCellBasis, isInsideDisplayCellBlock } from "./displayBasis";

export interface VisualAtom {
  siteId: number;
  element: string;
  cell: Int3;
  basisIndex: number;
  type: string;
  color?: number;
  position: Vec3;
}

export interface VisualBasisData {
  a: Vec3;
  b: Vec3;
  c: Vec3;
  sites: AtomSite[];
}

export interface CellRange1D {
  start: number;
  end: number;
}

export interface VisualCellRanges {
  x: CellRange1D;
  y: CellRange1D;
  z: CellRange1D;
}

export function cellRangeForAxis(size: number): CellRange1D {
  const n = sanitizeCellCount(size);
  const start = -Math.floor(n / 2);
  const end = start + n - 1;
  return { start, end };
}

export function sanitizeCellCount(size: number): number {
  if (!Number.isFinite(size)) return 3;
  return Math.max(1, Math.min(8, Math.round(size)));
}

export function visualCellRanges(lattice: Lattice, size: number): VisualCellRanges {
  const range = cellRangeForAxis(size);
  const z = lattice.dim === 2 ? { start: 0, end: 0 } : range;

  return {
    x: range,
    y: range,
    z,
  };
}

/**
 * Atom-generation basis.
 *
 * simpleCellBasis is guide-only and never used for atom coordinates.
 * conventionalBasis + visualSites is used for conventional motifs.
 * Otherwise primitive a,b,c + sites is used.
 */
export function getVisualBasisData(lattice: Lattice): VisualBasisData {
  const basis = lattice.conventionalBasis ?? {
    a: lattice.a,
    b: lattice.b,
    c: lattice.c,
  };

  return {
    a: basis.a,
    b: basis.b,
    c: basis.c,
    sites: lattice.visualSites ?? lattice.sites,
  };
}

export function visualCellOrigin(lattice: Lattice, cell: Int3): Vec3 {
  const visual = getVisualBasisData(lattice);
  return intToCart(cell, visual.a, visual.b, visual.c);
}

export function visualSiteOffset(lattice: Lattice, site: AtomSite): Vec3 {
  const visual = getVisualBasisData(lattice);
  return fracToCart(site.position, visual.a, visual.b, visual.c);
}

export function generateSupercellAtoms(lattice: Lattice, size: number): VisualAtom[] {
  return generateAtomsInsideDisplayGuideCells(lattice, size);
}

/**
 * Render only atoms inside or on the boundary of the blue display/guide cell block.
 *
 * This is different from "all atoms generated by visual basis cells":
 * atoms are generated from the physical/conventional visual basis, but filtered
 * against the displayed guide cell coordinates. This fixes the case where guide
 * cells and atom basis are different.
 */
export function generateAtomsInsideDisplayGuideCells(lattice: Lattice, size: number): VisualAtom[] {
  const atoms: VisualAtom[] = [];
  const visual = getVisualBasisData(lattice);
  const display = displayCellBasis(lattice);
  const ranges = visualCellRanges(lattice, size);

  const minDisplayFrac: Vec3 = [ranges.x.start, ranges.y.start, ranges.z.start];
  const maxDisplayFrac: Vec3 = [
    ranges.x.end + 1,
    ranges.y.end + 1,
    lattice.dim === 2 ? 0 : ranges.z.end + 1,
  ];

  // Estimate a compact search range in visual-basis cells.
  //
  // For most structures, a small margin is enough. For hexagonal-prism guide
  // cells, however, the displayed hex-center basis and the actual atom basis
  // are different. Example:
  //
  //   display A = primitive a + primitive b
  //   display B = -primitive a + 2 primitive b
  //
  // Therefore a displayed N-by-N hex-prism block can require atom primitive-cell
  // indices farther out than "display range +/- 2". With larger Display cells
  // per axis, the fixed margin caused some boundary atoms to never be generated
  // before clipping. Use a size-dependent conservative margin for that case.
  const n = sanitizeCellCount(size);
  const margin = lattice.displayCellShape === "hex_prism" && lattice.dim === 3
    ? 2 * n + 2
    : 2;

  const xStart = ranges.x.start - margin;
  const xEnd = ranges.x.end + margin + 1;
  const yStart = ranges.y.start - margin;
  const yEnd = ranges.y.end + margin + 1;
  const zStart = lattice.dim === 2 ? 0 : ranges.z.start - margin;
  const zEnd = lattice.dim === 2 ? 0 : ranges.z.end + margin + 1;

  const seen = new Set<string>();

  for (let i = xStart; i <= xEnd; i++) {
    for (let j = yStart; j <= yEnd; j++) {
      for (let k = zStart; k <= zEnd; k++) {
        visual.sites.forEach((site, basisIndex) => {
          const f: Vec3 = [
            i + site.position[0],
            j + site.position[1],
            lattice.dim === 2 ? 0 : k + site.position[2],
          ];

          const position = fracToCart(f, visual.a, visual.b, visual.c);

          if (!isInsideDisplayCellBlock(position, lattice, minDisplayFrac, maxDisplayFrac)) {
            return;
          }

          const key = `${roundKey(position[0])}:${roundKey(position[1])}:${roundKey(position[2])}:${site.type ?? site.element ?? "default"}`;
          if (seen.has(key)) return;
          seen.add(key);

          atoms.push({
            siteId: site.id,
            element: site.element,
            cell: [i, j, k],
            basisIndex,
            type: site.type ?? site.element ?? "default",
            color: site.color,
            position,
          });
        });
      }
    }
  }

  return atoms;
}

function roundKey(value: number): string {
  return value.toFixed(8);
}
